version: '3'
services:
  pg_query:
    build: pg_query
    image: enrich_pg_query
    environment:
      KAFKA_HOST: kafka
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ENTER_YOUR_PASSWORD
  g_query:
    build: g_query
    image: enrich_g_query
    environment:
      KAFKA_HOST: kafka
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ENTER_YOUR_PASSWORD
      API_KEY: ENTER_YOUR_API_KEY
  pg_update:
    build: pg_update
    image: enrich_pg_update
    environment:
      KAFKA_HOST: kafka
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ENTER_YOUR_PASSWORD
networks:
  default:
    external:
      name: geocode
